# Generated by Django 5.1.1 on 2024-09-12 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar'),
        ('funcionario', '0003_alter_funcionario_options_remove_funcionario_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funcionario.funcionario', verbose_name='Funcionario'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
