# Generated by Django 5.1.1 on 2024-09-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_funcionario_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='static/img/default_avatar.png', null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
