# Generated by Django 5.1.1 on 2024-09-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_hr_manager',
            field=models.BooleanField(blank=True, default=True, verbose_name='Gestor de RH ?'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_org_admin',
            field=models.BooleanField(blank=True, default=True, verbose_name='Admin. Org. ?'),
        ),
    ]
