# Generated by Django 5.1.1 on 2024-09-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_hr_manager_user_is_org_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_hr_manager',
            field=models.BooleanField(blank=True, default=False, verbose_name='Gestor de RH ?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_org_admin',
            field=models.BooleanField(blank=True, default=False, verbose_name='Admin. Org. ?'),
        ),
    ]
