# Generated by Django 5.1.1 on 2024-09-12 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classesalarial',
            options={'ordering': ['nome'], 'verbose_name': 'ClasseSalarial', 'verbose_name_plural': 'ClassesSalariais'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['cnpj', 'cnae'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='gestorrh',
            options={'verbose_name': 'GestorRH', 'verbose_name_plural': 'GestoresRH'},
        ),
        migrations.AlterModelOptions(
            name='porte',
            options={'verbose_name': 'Porte', 'verbose_name_plural': 'Portes'},
        ),
        migrations.AlterModelOptions(
            name='tabelasalarial',
            options={'ordering': ['versao', 'ativa'], 'verbose_name': 'TabelaSalarial', 'verbose_name_plural': 'TabelasSalariais'},
        ),
        migrations.AlterModelTable(
            name='classesalarial',
            table='classe_salarial',
        ),
        migrations.AlterModelTable(
            name='empresa',
            table='empresa',
        ),
        migrations.AlterModelTable(
            name='gestorrh',
            table='gestor_rh',
        ),
        migrations.AlterModelTable(
            name='porte',
            table='porte',
        ),
        migrations.AlterModelTable(
            name='tabelasalarial',
            table='tabela_salarial',
        ),
        migrations.CreateModel(
            name='Organizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado em')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('usuario_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Organizacao',
                'verbose_name_plural': 'Organizacoes',
                'db_table': 'organizacao',
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='organizacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.organizacao', verbose_name='Organizacao'),
        ),
    ]
