# Generated by Django 5.1.1 on 2024-09-24 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_rename_nome_organizacao_organizacao_nome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacao',
            name='organizacao_nome',
            field=models.CharField(max_length=50, verbose_name='Organização'),
        ),
        migrations.AlterField(
            model_name='organizacao',
            name='usuario_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizacoes', to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
    ]
