# Generated by Django 5.1.1 on 2024-09-25 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_alter_organizacao_organizacao_nome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestorrh',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestores', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
