# Generated by Django 5.1.1 on 2024-09-27 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_alter_gestorrh_empresa_alter_gestorrh_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacao',
            name='usuario_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizacoes', to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
    ]
