# Generated by Django 5.1.1 on 2024-09-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado em'),
        ),
    ]
