# Generated by Django 5.1.1 on 2024-09-12 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_funcionario_created_at_funcionario_modified_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['matricula', 'data_inicio'], 'verbose_name': 'Funcionario', 'verbose_name_plural': 'Funcionarios'},
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='usuario',
        ),
        migrations.AlterModelTable(
            name='funcionario',
            table='funcionario',
        ),
    ]
