# Generated by Django 5.1.1 on 2024-09-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0005_alter_funcionario_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='ativo',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='escolaridade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Escolaridade'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Prefiro não informar')], max_length=20, null=True, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='local_de_trabalho',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Local de Trabalho'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nacionalidade'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='raca_cor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Raça/Cor'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='regime_contrato',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Regime de Contrato'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
    ]
