name: deploy to EC2

on:
  push:
    branches:
      - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: set up SSH key and whitelist EC2 IP address
              run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                ssh-keyscan -H ${{ vars.HOST }} >> ~/.ssh/known_hosts
              shell: /usr/bin/bash -e {0}  
            
            - name: create .env file
              env: 
                ENV: ${{ secrets.DOTENV }}
                EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
              run: |
                echo "$ENV" > dotenv
                echo "EC2_USERNAME=$EC2_USERNAME" >> dotenv
                
            - name: Copy files to remote server
              env:
                HOST: ${{ vars.HOST }}
                EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
              run: |
                scp -r * $EC2_USERNAME@$HOST:/home/$EC2_USERNAME
            
            - name: SSH into remote server and deploy
              env:
                    HOST: ${{ vars.HOST }}
                    EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
              run: |
                    ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$HOST "chmod +x /home/$EC2_USERNAME/deploy.sh && /home/$EC2_USERNAME/deploy.sh"
            
            - name: Clean up SSH key
              run: |
                rm ~/.ssh/id_rsa
                rm ~/.ssh/known_hosts
            